### ISSUE TITLE
Typing issue

### ISSUE THREAD

**Issue by q-wertz** [madphysicist/haggis#12]
Not sure if this belongs here or to the `logging` library but maybe you have also experienced this.

I add a `trace` level logger to the logging library using your library. Automatically the method is added. The problem is, that the type checker does not know about it because it happens in runtime.

Do you have any solution for this? Adding `# type: ignore` in every line where I use the `logging.trace(…)` is not very feasible.

```python
import logging
import haggis.logs

haggis.logs.add_trace_level(haggis.logs.KEEP)

logger: logging.Logger = logging.getLogger(__name__)

logger.trace("Test")
```

```
[q-wertz@hoth testproject]$ mypy test.py
test.py:8: error: "Logger" has no attribute "trace"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by madphysicist** [comment]
Thanks for bringing this to my attention. I didn't really have anything besides CPython in mind when I wrote haggis, which may be a problem down the line. I'll do some research to see how I can fix. My first stab shows that one approach may be to subclass the existing logger class, e.g. https://stackoverflow.com/q/70199661/2988730. The issue with subclassing is that it will not affect any existing loggers. If my research does not yield any viable solutions, my fix will be a detailed note explaining that `logs` does not work with mypy.

**Comment by q-wertz** [comment]
Thanks for looking into this. 

In my personal opinion the current status is better than subclasing the logger…

**Comment by q-wertz** [comment]
I currently append `# type: ignore[attr-defined]` to each line where I use `logger.trace(…)`.

Not very convenient but maybe to only solution where all other type hints are least affected

**Comment by madphysicist** [comment]
It looks like mypy does not and will likely never support monkeypatching. I'm going to add a note to the docs to add `# type: ignore[attr-defined]` if you want to use the methods, but that generally these methods are not mypy-compatible.

**Comment by q-wertz** [comment]
Found this one: https://sam.hooke.me/note/2020/03/mypy-and-verbose-logging/#solution

But would only work for your added `trace` level and not the dynamic ones and it is not really a good solution…

**Comment by madphysicist** [comment]
Very neat. I don't have the luxury of installing a local partial stub
package, but I wonder if I can get something working anyway.
