### ISSUE TITLE
[Bug] add_logging_level 

### ISSUE THREAD

**Issue by aress31** [madphysicist/haggis#6]
Hi @madphysicist,

I am using the `logs` module, namely `add_logging_level` and that results in the following error:

```python
ValueError: Formatting field not found in record: 'level_name'
Call stack:
  File "C:\Users\REDACTED", line 92, in <module>
    main()
  File "C:\Users\REDACTED", line 25, in main
    logging.success("test")
  File "C:\Users\REDACTED\.venv\lib\site-packages\haggis\logs.py", line 197, in for_logging_module
    logging.log(level_num, *args, **kwargs)
Message: 'test'
Arguments: ()
```

Here is my code:

```python
import coloredlogs
import logging
from haggis import logs

def init_logger(log_level):
    coloredlogs.install(fmt="%(level_name)s %(message)s",
                        level=logging.getLevelName(log_level))

    logs.add_logging_level('TRACE', logging.DEBUG - 5)
    logs.add_logging_level('SUCCESS', logging.INFO - 5)

    logging.trace('so did this')

    logging.getLogger('ccxt').setLevel(logging.ERROR)
    logging.getLogger('requests').setLevel(logging.ERROR)
    logging.getLogger('urllib3').setLevel(logging.ERROR)
    logging.getLogger('vectorbt').setLevel(logging.ERROR)
```

Any help?

EDIT: It seems that it got to do with my custom format `%(level_name)s %(message)s`, when removing it works, however, it is a project requirement to log the messages using this format. Is it possible to tweak your lib to support custom formats?

**Comment by madphysicist** [comment]
@aress31. Apologies for the late reply. First of all, thanks for taking the time to report this issue with good details. I'm always happily surprised when someone uses my work at all, and doubly so when they help!

Could you tell me what version of python and haggis you are using? I haven't updated the logger code in a long time, so this will be a good opportunity to revisit it. I want to make sure that I test your issue in a way that works for you.

**Comment by aress31** [comment]
Hi @madphysicist - Thanks for the reply, I used Pyrhon 3.10 and the latest version of haggis. I refactoring my code so don't have the exact version anymore. Hope that helps.

**Comment by madphysicist** [comment]
@aress. Thank you. The logging module hasn't changed in a long time, so that's sufficient. I will look into the issue ASAP and let you know when I've resolved it.

**Comment by madphysicist** [comment]
@aress31 Sorry again for the late reply. Looking at the documentation of `LogRecord` here: https://docs.python.org/3/library/logging.html#logrecord-attributes, I don't see an attribute named `level_name`. I do however see one named `levelname`. Could you try running with the line below and let me know if it fixes your issue?
```
coloredlogs.install(fmt="%(levelname)s %(message)s",
                    level=logging.getLevelName(log_level))
```

**Comment by aress31** [comment]
Hi @madphysicist - Many thanks for following up on that, I have changed `level_name` to `levelname` and it worked. :)
