### ISSUE TITLE
logging.LoggerAdapter does not recognize the new added level

### ISSUE THREAD

**Issue by marcjammet** [madphysicist/haggis#7]
```import logging.config
import logging
from haggis import logs

class JobIdAdapter(logging.LoggerAdapter):
    def process(self,msg,kwargs):
        id = kwargs.pop('id', self.extra['id'])
        return '[%s] %s' % (id, msg), kwargs

conf_dict = {
    'version': 1,
    'formatters': {'simple': {'format': '%(asctime)s - %(module)s - %(levelname)s - %(message)s'}},
    'handlers': {
                'console': {
                    'class': 'logging.StreamHandler', 'formatter': 'simple', 'stream': 'ext://sys.stdout'
                    },
                'mxf': {
                    'class': 'logging.handlers.TimedRotatingFileHandler',
                    'formatter': 'simple',
                    'filename': '/xinet/Hotfolders/Logs/mxf.log',
                    'when': 'midnight',
                    'interval': 1,
                    'backupCount': 7,
                    'encoding': 'utf-8'
                    },
                'hfx': {
                     'class': 'logging.handlers.MemoryHandler',
                     'flushLevel': 60,
                     'formatter': 'simple',
                     'capacity': 1000,
                     'target': 'mxf',
                     'flushOnClose': True
                    }
                },
    'loggers': {
            'mxf': {'level': 'DEBUG', 'handlers': ['mxf'], 'propagate': True},
            'hfx': {'level': 'DEBUG', 'handlers': ['hfx'], 'propagate': True}},
            'root': {'level': 'DEBUG', 'handlers': ['console']}
                }

logging.config.dictConfig(conf_dict)
logs.add_logging_level('DETAIL',15)
hfx_log = logging.getLogger("hfx")
hfx_log = JobIdAdapter(hfx_log,{'id':10000})

hfx_log.detail('Some message',{'id':10})
```
Got this error:

```Traceback (most recent call last):
  File "/cogito/MaxiFolders/x.py", line 45, in <module>
    hfx_log.detail('Some message',{'id':10})
AttributeError: 'JobIdAdapter' object has no attribute 'detail'

Process finished with exit code 1
```

What can be done about this. 
Thank you for your help.

**Comment by madphysicist** [comment]
@marcjammet Thank you for the detailed feedback and bringing this to my attention. I'm always happy when people find my library useful, and even more so when they help me improve it. At the moment, I am only monkey-patching the Logger class and not LoggerAdapter. The "right" answer, in my opinion, would be to monkey-patch both. I'll need to revisit the logging code to do so properly, since I haven't looked at it for a long time. My plan is to release the update as part of version 0.8.0. Forgive me if it takes some time though.

**Comment by marcjammet** [comment]
Thank you for your help. I can wait, I found a workaround in the mean time, but you're right it’s better if both class are patched.

class JobIdAdapter(logging.LoggerAdapter):

    def detail(self,msg, *args, **kwargs):
        self.log(logging.DETAIL, msg, *args, **kwargs)

Cordialement
--
Marc Jammet
--
Mob : +33  6 85 96 15 16
eMail:  ***@***.***
Web :   https://www.cogito.digital                                                          

Le 25 octobre 2022 à 15:19:33, Joseph Fox-Rabinovitz ***@***.***) a écrit:

@marcjammet Thank you for bringing this to my attention. At the moment, I am only monkey-patching the Logger class and not LoggerAdapter. The "right" answer, in my opinion, would be to monkey-patch both. I'll need to revisit the logging code to do so properly, since I haven't looked at it for a long time. My plan is to release the update as part of version 0.8.0. Forgive me if it takes some time though.

**Comment by madphysicist** [comment]
I've taken a detailed look at what the existing CPython implementation is doing and added it to my monkeypatching routines. Will make a proper PR once I've written some simple unit tests.

**Comment by madphysicist** [comment]
I've merged #11 and added it to version 0.8.0, which is now available on PyPi. Please let me know if there is anything missing. I will await your closure of the ticket if you feel that it's justified.

**Comment by madphysicist** [comment]
I am considering adding a `add_detail_level` similar to `add_trace_level` to the `logs` module now.

**Comment by marcjammet** [comment]
This is a very good idea Envoyé de mon iPhoneLe 6 nov. 2022 à 22:02, Joseph Fox-Rabinovitz ***@***.***> a écrit :﻿
I am considering adding a add_detail_level similar to add_trace_level to the logs module now.

**Comment by madphysicist** [comment]
How do you feel about closing off this ticket?

**Comment by madphysicist** [comment]
I've added a `add_detail_level` function and some more updates in the latest `dev` branch, which will go into `0.9.0` presumably, once I decide to release it. You can drop in the current `logs.py` over whatever version you have installed if you want to use it immediately.

**Comment by marcjammet** [comment]
Thank you for your commitment 
Fully apreciated

**Comment by madphysicist** [comment]
@marcjammet Thanks for the first real feature request to haggis! It was exciting to find out that someone else is using it.
